#!/usr/bin/env python3
"""Build Data/Loot.lua: what a dungeon quest rewards, and what its bosses drop.

Usage: python3 tools/build_loot.py [--db tools/cache/wowsims-classic/db.json]

Source is the WoWSims Classic item database (MIT), which carries a source for most items:
which quest rewards it, or which creature in which zone drops it. Forever's own loot tables are
server side and appear nowhere public, so this is Classic data: right for the nineteen Classic
dungeons, and the closest thing to right for Forever's changes to them. Boss drops are cut to
rare and better, because Forever's bosses no longer drop greens.
"""
import argparse
import collections
import datetime
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_data import lua_string  # noqa: E402
from build_dungeons import DUNGEONS  # noqa: E402

MIN_DROP_QUALITY = 3  # rare. Forever's bosses drop no greens.
QUEST_LINE = re.compile(r'\{ id = (\d+), name = "')
DUNGEON_LINE = re.compile(r'\n  \{ key = "([^"]+)"')


def dungeon_quests(path):
    """{dungeon key: [quest id]} from the generated dungeon file.

    Prerequisite steps count: they are drawn in the tree like any other, so their rewards are
    worth knowing too."""
    with open(path, encoding="utf-8") as handle:
        text = handle.read()
    out, key = collections.OrderedDict(), None
    for line in text.splitlines():
        found = DUNGEON_LINE.match("\n" + line)
        if found:
            key = found.group(1)
            out[key] = []
        elif key:
            for quest in QUEST_LINE.finditer(line):
                out[key].append(int(quest.group(1)))
    return out


def item_row(item):
    return (item["id"], item.get("name") or "?", item.get("quality") or 0, item.get("ilvl") or 0)


def build(db, quests_by_dungeon):
    items = db["items"]
    npc_names = {n["id"]: n.get("name") for n in db.get("npcs", [])}

    by_quest = collections.defaultdict(list)
    by_zone = collections.defaultdict(lambda: collections.defaultdict(list))
    for item in items:
        for source in item.get("sources") or []:
            quest = source.get("quest")
            if quest and quest.get("id"):
                by_quest[quest["id"]].append(item)
            drop = source.get("drop")
            if drop and drop.get("zoneId"):
                by_zone[drop["zoneId"]][drop.get("npcId") or 0].append(item)

    wanted = {q for ids in quests_by_dungeon.values() for q in ids}
    rewards = {}
    for quest_id in sorted(wanted):
        found = by_quest.get(quest_id)
        if found:
            rows = sorted({item_row(i) for i in found}, key=lambda r: (-r[2], -r[3], r[1]))
            rewards[quest_id] = rows

    loot = collections.OrderedDict()
    for key, name, zone, lo, hi, faction, aliases in DUNGEONS:
        bosses = []
        for npc_id, found in by_zone.get(zone, {}).items():
            rows = sorted({item_row(i) for i in found if (i.get("quality") or 0) >= MIN_DROP_QUALITY},
                          key=lambda r: (-r[3], r[1]))
            if rows:
                bosses.append({"npc": npc_id, "name": npc_names.get(npc_id) or "Somewhere inside",
                               "items": rows})
        bosses.sort(key=lambda b: (b["npc"] == 0, b["name"]))
        if bosses:
            loot[key] = bosses
    return rewards, loot


def emit(rewards, loot, generated):
    items = sum(len(r) for r in rewards.values()) + sum(len(b["items"]) for d in loot.values() for b in d)
    lines = ["local _, ns = ...", "",
             "-- GENERATED by tools/build_loot.py from the WoWSims Classic database; do not edit by hand.",
             "-- Classic data. Forever's own loot tables are server side; the addon marks anything a",
             "-- player has actually seen drop from its own records instead.",
             "ns.LootInfo = { generated = %s, quests = %d, dungeons = %d, items = %d, minQuality = %d }" % (
                 lua_string(generated), len(rewards), len(loot), items, MIN_DROP_QUALITY),
             "", "-- [questID] = { { itemID, name, quality, itemLevel }, ... }", "ns.QuestRewards = {"]
    for quest_id in sorted(rewards):
        row = ", ".join("{ %d, %s, %d, %d }" % (i, lua_string(n), q, l) for i, n, q, l in rewards[quest_id])
        lines.append("  [%d] = { %s }," % (quest_id, row))
    lines.append("}")
    lines.append("")
    lines.append("-- [dungeon key] = { { npc = id, name = , items = { { itemID, name, quality, itemLevel } } } }")
    lines.append("ns.DungeonLoot = {")
    for key, bosses in loot.items():
        lines.append("  %s = {" % key)
        for boss in bosses:
            lines.append("    { npc = %d, name = %s, items = {" % (boss["npc"], lua_string(boss["name"])))
            for i, n, q, l in boss["items"]:
                lines.append("      { %d, %s, %d, %d }," % (i, lua_string(n), q, l))
            lines.append("    } },")
        lines.append("  },")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main(argv=None):
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", default=os.path.join(root, "tools", "cache", "wowsims-classic", "db.json"))
    parser.add_argument("--dungeons", default=os.path.join(root, "Data", "Dungeons.lua"))
    parser.add_argument("--out", default=os.path.join(root, "Data", "Loot.lua"))
    parser.add_argument("--with-drops", action="store_true",
                        help="also ship the boss drop tables (Classic's, until Forever's are recorded)")
    args = parser.parse_args(argv)

    with open(args.db, encoding="utf-8") as f:
        db = json.load(f)
    quests_by_dungeon = dungeon_quests(args.dungeons)
    rewards, loot = build(db, quests_by_dungeon)
    if not args.with_drops:
        loot = collections.OrderedDict()
    text = emit(rewards, loot, datetime.date.today().isoformat())
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(text)

    every = {q for ids in quests_by_dungeon.values() for q in ids}
    print("%d of %d dungeon quests and their earlier steps have a known reward" % (len(rewards), len(every)))
    for key, bosses in loot.items():
        print("  %-26s %2d bosses, %3d items" % (key, len(bosses), sum(len(b["items"]) for b in bosses)))
    print("written to %s" % args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
