#!/usr/bin/env python3
"""Regenerate ForeverBuddyScan/Data/QuestIDs.lua: every quest id the client knows about.

Source: QuestV2.db2 from wago.tools, which is just the list of ids - no names, no rewards, no
objectives. That is the point: the ids are what the scanner feeds to the server, which does
know the rest. Standard library only.

    python3 tools/build_questids.py --build 1.60.1.70178
"""
import argparse
import csv
import datetime
import io
import os

from build_data import fetch, lua_string

WAGO_URL = "https://wago.tools/db2/{table}/csv?build={build}"
PER_LINE = 20


def quest_ids(text):
    return sorted({int(row["ID"]) for row in csv.DictReader(io.StringIO(text)) if row.get("ID")})


def emit(ids, build, generated):
    lines = [
        "local _, ns = ...",
        "",
        "-- GENERATED by ForeverBuddy's tools/build_questids.py from QuestV2.db2 (wago.tools).",
        "-- Every quest id the client knows about. The scanner asks the server about each one.",
        "ns.QuestIDsInfo = { build = %s, generated = %s, count = %d }" % (
            lua_string(build), lua_string(generated), len(ids)),
        "",
        "ns.QuestIDs = {",
    ]
    for i in range(0, len(ids), PER_LINE):
        lines.append("  " + ", ".join(str(q) for q in ids[i:i + PER_LINE]) + ",")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main(argv=None):
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    default_out = os.path.join(os.path.dirname(root), "ForeverBuddyScan", "Data", "QuestIDs.lua")
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--build", required=True, help="client build number, e.g. 1.60.1.70178")
    parser.add_argument("--out", default=default_out)
    parser.add_argument("--cache", default=os.path.join(root, "tools", "cache"))
    args = parser.parse_args(argv)

    text = fetch(WAGO_URL.format(table="QuestV2", build=args.build),
                 os.path.join(args.cache, args.build, "QuestV2.csv"))
    ids = quest_ids(text)
    if len(ids) < 1000:
        raise SystemExit("only %d ids for build %s: wrong build number?" % (len(ids), args.build))
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(emit(ids, args.build, datetime.date.today().isoformat()))
    print("%s: %d quest ids -> %s" % (args.build, len(ids), args.out))


if __name__ == "__main__":
    main()
