#!/usr/bin/env python3
"""Regenerate Data/Crafting.lua: what every craftable item is made of, for every profession.

    python3 tools/build_crafting.py --build 1.60.1.70178

Data/Recipes.lua answers "what is this reagent used in". This answers the other way round, which
is what a shopping list needs: given an item, what goes into it, how many that makes, and what
skill it wants. Four client tables, all of which we already download:

  SpellReagents      what a recipe consumes
  SpellEffect        effect 24 is "create item"; EffectBasePointsF is how many it makes, which
                     is 1 for a Mithril Bar and 200 for a stack of slugs. EffectBasePoints,
                     the obvious-looking column, is empty and reads as 1 for everything.
  SkillLineAbility   which profession, and TrivialSkillLineRankLow, which is the skill the
                     recipe actually needs. MinSkillLineRank is 1 for every recipe in the game
                     and tells you nothing.
  SkillLine          the profession's name

Standard library only.
"""
import argparse
import csv
import datetime
import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_data import fetch, lua_string  # noqa: E402

WAGO_URL = "https://wago.tools/db2/{table}/csv?build={build}"
TABLES = ("SpellReagents", "SpellEffect", "SkillLineAbility", "SkillLine", "SpellName")
EFFECT_CREATE_ITEM = "24"
PROFESSION_CATEGORIES = {"9", "11"}  # SkillLine.CategoryID: 9 secondary, 11 primary

# The categories also hold Blizzard's own scratch lines - "Test Profession [DNT]" has a Smelt
# Copper of its own, and it was winning on skill level and turning up in players' lists. Only
# the professions a character can actually have are allowed through.
REAL_PROFESSIONS = {
    "Alchemy", "Blacksmithing", "Cooking", "Enchanting", "Engineering", "First Aid", "Fishing",
    "Herbalism", "Leatherworking", "Mining", "Poisons", "Skinning", "Tailoring",
}
REAGENT_SLOTS = 8


def read_csv(text):
    return list(csv.DictReader(io.StringIO(text)))


def build(tables):
    professions = {r["ID"]: r["DisplayName_lang"] for r in tables["SkillLine"]
                   if r["CategoryID"] in PROFESSION_CATEGORIES and r["DisplayName_lang"] in REAL_PROFESSIONS}
    spell_names = {r["ID"]: r["Name_lang"] for r in tables["SpellName"]}

    # A spell can sit on more than one skill line; keep the one that is a profession, and with
    # it the skill the recipe needs.
    skill_of, rank_of = {}, {}
    for row in tables["SkillLineAbility"]:
        if row["SkillLine"] in professions and row["Spell"] not in skill_of:
            skill_of[row["Spell"]] = row["SkillLine"]
            rank_of[row["Spell"]] = int(row["TrivialSkillLineRankLow"] or 0)

    creates, makes = {}, {}
    for row in tables["SpellEffect"]:
        if row["Effect"] != EFFECT_CREATE_ITEM:
            continue
        spell = row["SpellID"]
        if spell in creates:
            continue
        creates[spell] = int(row["EffectItemType"] or 0)
        amount = row.get("EffectBasePointsF") or row.get("EffectBasePoints") or "1"
        makes[spell] = max(1, int(float(amount)))

    reagents = {}
    for row in tables["SpellReagents"]:
        items = []
        for i in range(REAGENT_SLOTS):
            item = int(row["Reagent_%d" % i] or 0)
            count = int(row["ReagentCount_%d" % i] or 0)
            if item > 0 and count > 0:
                items.append((item, count))
        if items:
            reagents[row["SpellID"]] = items

    out = {}
    for spell, item in creates.items():
        if not (item and spell in reagents and spell in skill_of):
            continue
        # Two recipes can make the same item (a Horde and an Alliance version, say). The one
        # that asks for the lowest skill is the one somebody will actually use.
        record = {"spell": int(spell), "item": item, "makes": makes.get(spell, 1),
                  "profession": professions[skill_of[spell]], "skill": rank_of.get(spell, 0),
                  "name": spell_names.get(spell, ""), "reagents": sorted(reagents[spell])}
        if item not in out or record["skill"] < out[item]["skill"]:
            out[item] = record
    return out


def emit(recipes, info):
    lines = [
        "local _, ns = ...",
        "",
        "-- GENERATED by tools/build_crafting.py; do not edit by hand.",
        "-- What each craftable item is made of. The shopping list walks this; Data/Recipes.lua",
        "-- answers the opposite question and is built from the other direction.",
        "ns.CraftingInfo = { build = %s, generated = %s, recipes = %d }" % (
            lua_string(info["build"]), lua_string(info["generated"]), len(recipes)),
        "",
        "ns.Crafting = {",
        "  -- [itemID] = { spell, recipeName, profession, skill, makes, { { reagentID, count }, ... } }",
    ]
    for item in sorted(recipes):
        r = recipes[item]
        reagents = ", ".join("{ %d, %d }" % pair for pair in r["reagents"])
        lines.append("  [%d] = { %d, %s, %s, %d, %d, { %s } }," % (
            item, r["spell"], lua_string(r["name"]), lua_string(r["profession"]),
            r["skill"], r["makes"], reagents))
    lines.append("}")
    return "\n".join(lines) + "\n"


def main(argv=None):
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--build", required=True)
    parser.add_argument("--out", default=os.path.join(root, "Data", "Crafting.lua"))
    parser.add_argument("--cache", default=os.path.join(root, "tools", "cache"))
    args = parser.parse_args(argv)

    tables = {}
    for table in TABLES:
        text = fetch(WAGO_URL.format(table=table, build=args.build),
                     os.path.join(args.cache, args.build, table + ".csv"))
        tables[table] = read_csv(text)
    recipes = build(tables)
    if len(recipes) < 1000:
        raise SystemExit("only %d recipes for build %s: wrong build number?" % (len(recipes), args.build))

    with open(args.out, "w", encoding="utf-8") as f:
        f.write(emit(recipes, {"build": args.build, "generated": datetime.date.today().isoformat()}))

    counts = {}
    for r in recipes.values():
        counts[r["profession"]] = counts.get(r["profession"], 0) + 1
    print("%s: %d craftable items -> %s" % (args.build, len(recipes), args.out))
    for profession, n in sorted(counts.items(), key=lambda kv: -kv[1]):
        print("  %-22s %d" % (profession, n))


if __name__ == "__main__":
    main()
