#!/usr/bin/env python3
"""Regenerate Data/Weights.lua: per-spec stat weights pulled from the WoWSims simulators.

Source: https://github.com/wowsims/<game> (MIT). Every spec's ui/<spec>/sim.ts declares
`epWeights: Stats.fromMap({ [Stat.StatStrength]: 2.51, ... }, { [PseudoStat.PseudoStatMainHandDps]: 11.92, ... })`.
Standard library only.

    python3 tools/build_weights.py --game classic
"""
import argparse
import datetime
import json
import os
import re
import sys
import urllib.request

from build_data import fetch, lua_string

GAMES = ("classic", "sod", "tbc", "wotlk")
TREE_URL = "https://api.github.com/repos/wowsims/{game}/git/trees/master?recursive=1"
COMMIT_URL = "https://api.github.com/repos/wowsims/{game}/commits/master"
RAW_URL = "https://raw.githubusercontent.com/wowsims/{game}/master/{path}"
CLASSES = ("Warrior", "Paladin", "Hunter", "Rogue", "Priest", "Shaman", "Mage", "Warlock", "Druid")
EXCLUDED_SPECS = {"WardenShaman"}  # tank shaman: not a spec we plan to support yet

# Resistances are dropped. WoWSims' presets are written for raid fights that demand a resistance
# set, and nine specs carry a leftover FireResistance 0.5 from Molten Core gearing, which would
# make a fire resistance roll read as an upgrade on a level 20 dungeon drop. Armour and defence
# stay: those are real for tanks at any level.
EXCLUDED_STATS = {"FireResistance", "FrostResistance", "NatureResistance",
                  "ShadowResistance", "ArcaneResistance"}

_SPEC = re.compile(r"Spec\.Spec([A-Za-z]+)")
_EP_START = re.compile(r"epWeights:\s*Stats\.fromMap\(")
_ENTRY = re.compile(r"\[(?:PseudoStat\.PseudoStat|Stat\.Stat)([A-Za-z0-9]+)\]\s*:\s*(-?\d+(?:\.\d+)?)")
_SIM_PATH = re.compile(r"^ui/([a-z_]+)/sim\.ts$")


def _balanced(text, start):
    """text[start] must be '{'. Returns (inner text, index just after the matching '}')."""
    depth = 0
    for i in range(start, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[start + 1:i], i + 1
    raise ValueError("unbalanced braces")


def _entries(inner):
    return {name: float(value) for name, value in _ENTRY.findall(inner)
            if name not in EXCLUDED_STATS}


def parse_ep_weights(source):
    """Return (stats, pseudo) dicts from a sim.ts, or None when it declares no epWeights."""
    m = _EP_START.search(source)
    if not m:
        return None
    first = source.index("{", m.end())
    inner, after = _balanced(source, first)
    stats = _entries(inner)
    pseudo = {}
    k = after
    while k < len(source) and source[k] in " \t\r\n":
        k += 1
    if k < len(source) and source[k] == ",":
        k += 1
        while k < len(source) and source[k] in " \t\r\n":
            k += 1
        if k < len(source) and source[k] == "{":
            second, _ = _balanced(source, k)
            pseudo = _entries(second)
    return stats, pseudo


def spec_key(source):
    m = _SPEC.search(source)
    return m.group(1) if m else None


def class_token(key):
    for name in CLASSES:
        if name in key:
            return name.upper()
    return "UNKNOWN"


def display_name(key):
    return re.sub(r"(?<=[a-z])(?=[A-Z])", " ", key)


def parse_sim(source, path=None):
    """Return a spec record {key, class, name, stats, pseudo, path} or None."""
    key = spec_key(source)
    weights = parse_ep_weights(source)
    if not key or not weights:
        return None
    stats, pseudo = weights
    return {"key": key, "class": class_token(key), "name": display_name(key), "stats": stats,
            "pseudo": pseudo, "path": path}


def _lua_map(values):
    if not values:
        return "{ }"
    parts = ["%s = %s" % (name, ("%g" % values[name])) for name in sorted(values)]
    return "{ " + ", ".join(parts) + " }"


def emit_weights(specs, info):
    lines = [
        "local _, ns = ...",
        "",
        "-- GENERATED by tools/build_weights.py from WoWSims (https://github.com/wowsims, MIT); do not edit by hand.",
        "-- Resistance stats are left out on purpose: see EXCLUDED_STATS in the generator.",
        "ns.WeightsInfo = { game = %s, generated = %s, specs = %d, repo = %s, commit = %s }" % (
            lua_string(info["game"]), lua_string(info["generated"]), len(specs),
            lua_string(info.get("repo") or "?"), lua_string(info.get("commit") or "?")),
        "",
        "ns.Weights = {",
        "  -- [specKey] = { class = CLASSTOKEN, name = display name, stats = { StatName = weight, ... }, pseudo = { ... } }",
    ]
    for spec in sorted(specs, key=lambda s: s["key"]):
        lines.append("  [%s] = { class = %s, name = %s, source = %s, stats = %s, pseudo = %s }," % (
            lua_string(spec["key"]), lua_string(spec["class"]), lua_string(spec["name"]),
            lua_string(spec.get("path") or "?"), _lua_map(spec["stats"]), _lua_map(spec["pseudo"])))
    lines.append("}")
    return "\n".join(lines) + "\n"


def head_commit(game):
    """The commit the weights were read at, so a number in the workbook can be traced back."""
    try:
        text = urllib.request.urlopen(urllib.request.Request(
            COMMIT_URL.format(game=game), headers={"User-Agent": "ForeverBuddy build_weights.py"}),
            timeout=30).read().decode("utf-8")
        return json.loads(text)["sha"][:12]
    except Exception:  # provenance is nice to have, never a reason to fail the build
        return "?"


def sim_paths(tree_json):
    paths = []
    for entry in json.loads(tree_json)["tree"]:
        m = _SIM_PATH.match(entry["path"])
        if m and m.group(1) != "core":
            paths.append(entry["path"])
    return sorted(paths)


def main(argv=None):
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--game", default="classic", choices=GAMES)
    parser.add_argument("--out", default=os.path.join(root, "Data", "Weights.lua"))
    parser.add_argument("--cache", default=os.path.join(root, "tools", "cache"))
    args = parser.parse_args(argv)

    cache = os.path.join(args.cache, "wowsims-" + args.game)
    tree = fetch(TREE_URL.format(game=args.game), os.path.join(cache, "tree.json"))
    specs, skipped = [], []
    for path in sim_paths(tree):
        source = fetch(RAW_URL.format(game=args.game, path=path), os.path.join(cache, path.replace("/", "_")))
        record = parse_sim(source, path)
        if record and record["key"] in EXCLUDED_SPECS:
            skipped.append(path + " (excluded)")
        elif record:
            specs.append(record)
        else:
            skipped.append(path)
    if not specs:
        sys.exit("no epWeights found for " + args.game)
    info = {"game": args.game, "generated": datetime.date.today().isoformat(),
            "repo": "wowsims/" + args.game, "commit": head_commit(args.game)}
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(emit_weights(specs, info))
    print("%s: %d specs -> %s" % (args.game, len(specs), args.out))
    for path in skipped:
        print("  skipped (no epWeights): " + path)


if __name__ == "__main__":
    main()
